using Avalonia;
using Avalonia.Controls;
using Avalonia.Media;
using RGDSCapture.Core;

namespace RGDSCapture.Services
{
    /// <summary>
    /// Swaps the active theme dictionary at runtime. The palette is always
    /// merged dictionary index 0 (see App.axaml); control styles in
    /// Themes/Controls.axaml reference colors via DynamicResource, so
    /// everything restyles live with no restart.
    ///
    /// Palettes are generated by <see cref="PaletteBuilder"/> rather than
    /// loaded from disk — Themes/Dark.axaml only exists as the design-time and
    /// pre-startup fallback.
    /// </summary>
    public static class ThemeService
    {
        public static ThemePreset Current { get; private set; } = ThemeCatalog.Default;

        /// <summary>Accent override in force, or null when using the preset's own accent.</summary>
        public static Color? CustomAccent { get; private set; }

        /// <summary>
        /// Raised after the palette changes. The Windows build has no
        /// equivalent: WPF re-resolves a DynamicResource when the dictionary
        /// holding it is replaced, whereas Avalonia resolves against the
        /// merged collection, so anything holding a brush it fetched in code
        /// (rather than through a binding) has to be told to fetch it again.
        /// </summary>
        public static event Action? Changed;

        public static void Apply(ThemePreset preset, Color? accentOverride = null)
        {
            var dict = PaletteBuilder.Build(preset, accentOverride);

            var merged = Application.Current!.Resources.MergedDictionaries;
            if (merged.Count > 0) merged[0] = dict;
            else merged.Add(dict);

            Current = preset;
            CustomAccent = accentOverride;

            Changed?.Invoke();
        }

        /// <summary>Applies the theme recorded in settings, tolerating stale ids.</summary>
        public static void ApplyFrom(AppSettings settings)
        {
            var preset = ThemeCatalog.Resolve(settings.ThemeId);

            Color? accent = null;
            if (!string.IsNullOrWhiteSpace(settings.CustomAccent))
                accent = PaletteBuilder.ParseHex(settings.CustomAccent);

            Apply(preset, accent);
        }

        /// <summary>The accent actually in effect — the override if set, else the preset's.</summary>
        public static Color EffectiveAccent =>
            CustomAccent ?? PaletteBuilder.ParseHex(Current.Accent);

        /// <summary>
        /// Looks a palette brush up by key, for the few places that need one
        /// in code rather than through a binding. Falls back to transparent
        /// rather than throwing, so a missing key degrades to an invisible
        /// element instead of taking the window down.
        /// </summary>
        public static IBrush Brush(string key) =>
            Application.Current?.TryFindResource(key, out object? value) == true
            && value is IBrush brush
                ? brush
                : Brushes.Transparent;
    }
}
